### ISSUE TITLE
Minor: Magnifying glass icon animation

### ISSUE THREAD

**Issue by ima007** [derrickshowers/RecommendIt#10]
To reproduce:
* Go to add a new recommendation
* tap location name to bring up the typeahead
* Tap on "Narrow results by city"
* Tap "cancel" on the enter-a-city prompt that comes up
* Notice that the magnifying glass is still in the center of the search box. It does animate back once I've focused into the search box.

Expected behavior:
* Magnifying glass probably shouldn't animate when the enter-a-city dialog comes up, or it should go back as soon as the dialog is closed.

**Comment by derrickshowers** [comment]
Yeah, I noticed this as well, also takes the focus away from the cancel
button which is a bit weird (if you want to cancel, you have to tap it
twice). I think I should be able to make the search bar the 'first
responder' once the alert is gone.

Thanks!
