### ISSUE TITLE
As a user, I'd like to edit my notes for a location that I've already saved to my list.

### ISSUE THREAD

**Issue by ima007** [derrickshowers/RecommendIt#11]
This could be an "Edit" text button in the top nav of the detail view for a restaurant, or a tappable "pencil icon" next to the user's notes on the description.

**Comment by derrickshowers** [comment]
Yeah, I concur. This seems pretty important, the only way to 'edit' right now is to delete and re-add (which is definitely not convenient). I'll put this on the top of the list for the next release!

**Comment by derrickshowers** [comment]
Done! Will be in the next release.
