### ISSUE TITLE
When manually changing city, the list of restaurants from the previous city still show up

### ISSUE THREAD

**Issue by ima007** [derrickshowers/RecommendIt#2]
To reproduce: 
* Location services turned on
* I think I started typing in the name of a restaurant in Mountain View
* Changed the location manually to "New York City"
* List of restaurants from Mountain View still showing up in the list
* I had to start typing something else to get new results

Expectation:
As soon as the city is changed, I'd expect the list of results to be empty, or be filled with results based on what has been typed in the search box.

**Comment by derrickshowers** [comment]
Fixed. Will be part of next release.
