### ISSUE TITLE
Swipe right to archive, swipe left to delete

### ISSUE THREAD

**Issue by ima007** [derrickshowers/RecommendIt#5]
Enhancement request: Have gestures on list items so that they can be archived by swiping right ("done"), or deleted by swiping left (kind of like Google Inbox or Mail).

**Comment by derrickshowers** [comment]
Going to close this one out as I implemented something similar that gives the user the ability to delete/archive without going to the detail page. Also added the 'bouncing' vertically which I think helps make it feel less like you want to swipe left/right.

Screenshot:
![ios_simulator_-_iphone_6_-_iphone_6___ios_8_1__12b411_](https://cloud.githubusercontent.com/assets/1372292/5809900/1455a932-9ff3-11e4-9552-b45e72fb869e.png)

Will be in the next build, let me know what you think!

**Comment by ima007** [comment]
This is awesome, I really like it!
