### ISSUE TITLE
Nitpick: Make "archive" a different color

### ISSUE THREAD

**Issue by ima007** [derrickshowers/RecommendIt#6]
Enhancement request: 
I think green" or blue would be a more inviting color for "archive".

**Comment by ima007** [comment]
nice!

**Comment by derrickshowers** [comment]
Not sure if I've figured out the colors I want, but wanted to keep the
'Yelp' button red to match their branding. I played around with variations
on the archive/delete buttons, but looks weird with 3 different colors.
I'll probably spice this page up a bit in a future version.
